### ISSUE TITLE
Android only？

### ISSUE THREAD

**Issue by Yunnathai** [472647301/react-native-dlna-player#1]

**Comment by 472647301** [comment]
DLNA service iOS only has real machine architecture

**Comment by Yunnathai** [comment]
oh...I hope your library can surpass react-native-video . ill be the tester and supporter. Have an early rest!

**Comment by 472647301** [comment]
Well, I'm still in the testing and experimental stage. This library is based on the combination of my react-native-dlna and react-native-byron-vlc, because react-native-dlna does not support arm64 architecture. project

**Comment by Yunnathai** [comment]
有没有兴趣支持下 farbic mode 新渲染。
